name: 'Call Webhook'
description: 'Call a webhook from an action'
inputs:
  URL:
    description: 'Webhook url to call'
    required: true
  PAT:
    description: 'Personal Access Token required to call webhook'
    required: true
  PAYLOAD:
    description: 'JSON data to send to the webhook'
runs:
  using: 'node12'
  main: 'index.js'